@startuml
'https://plantuml.com/class-diagram

object Webetu
object ApplicationJS
object www
object Proxy
object API
object ServiceBlockedData
object ServiceDataBase
object BDD

Webetu -- ApplicationJS
ApplicationJS --> www : Http request
ApplicationJS --> Proxy : Http request
Proxy --> ServiceBlockedData : RMI request
ServiceBlockedData --> API : Http request
Proxy --> ServiceDataBase : RMI request
ServiceDataBase --> BDD : SQL request

@enduml